baseURL: "https://formal-labs.github.io/"
title: Лаборатория формальной математики
locale: ru

enableInlineShortcodes: true
enableRobotsTXT: true

menu:
    main:
        - name: Семинар
          url: /
          weight: 1
        - name: Курс по теории типов
          url: /typetheory/
          weight: 2
        - name: Курс по теории категорий
          url: /categorytheory/
          weight: 3
        

params:
    description: "Лаборатория формальной математики"
    author: Лаборатория формальной математики

markup:
    goldmark:
        renderer:
            unsafe: true
